### PR TITLE
Only comment not supported tags

### PR DESCRIPTION
**Pull request by cmfcmf**
IMHO this is better than silently removing them.

### CODE REVIEW

**Comment by craigh** [comment]
I disagree only because there is no such functionality in Twig for "nocache" and I have intention to create a Twig function for "pagerendertime" so why keep them?

also - it is odd that I did not get a notification about your PR....

**Comment by cmfcmf** [comment]
Regarding {nocache}:
Then we need to check (if you haven't done so already)
1. why {nocache} is needed in Smarty 
2. if there is something similar in Twig or if it is not needed

Regarding {pagerendertime}: Even if there is no replacement, it is more clear to the theme author (who converts his theme), that this function does no longer exist.

**Comment by craigh** [comment]
[{nocache}](http://www.smarty.net/docs/en/language.function.nocache.tpl)
> {nocache} is used to disable caching of a template section. Every {nocache} must be paired with a matching {/nocache}.

from my research (and yes, I just spent 30 minutes looking + time before now) there is nothing similar in Twig. It appears Twig's caching mechanisms are less robust than smarty.

> it is more clear to the theme author..., that this function does no longer exist.

that's what the *diff* is for :-)

**Comment by cmfcmf** [comment]
> that's what the diff is for :-)

Right, I somehow forgot the diff.

**Pull request closed without merging**
